from window2 import Ui_MainWindow
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EHR2(object):
    #Open second window
    def openWindow (self):
        thing = self.CPR_inout.text()
        if thing == "1234567890":
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.window)
            self.window.show()

        else:
            #self.message = QMessageBox()
            # Custom Texts
            #self.message.setWindowTitle("Error")
            #self.message.setText("Please enter a CPR number")
            #self.message.setWindowIcon(QtGui.QIcon('logo.svg'))
            #self.message.setIcon(QMessageBox.Warning)
            #self.message.setStandardButtons(QMessageBox.Yes)
            #b = self.message.button(QMessageBox.Yes)
            b.setText("Restart")
            # Start the window and wait for a user input
            self.message.exec_()
            #QMessageBox.warning(self, "Error")



    def setupUi(self, EHR2):
        EHR2.setObjectName("EHR2")
        EHR2.resize(870, 600)
        self.centralwidget = QtWidgets.QWidget(parent=EHR2)
        self.centralwidget.setObjectName("centralwidget")
        self.Date_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.Date_widget.setGeometry(QtCore.QRect(10, 20, 201, 51))
        self.Date_widget.setObjectName("Date_widget")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.Date_widget)
        self.dateEdit.setGeometry(QtCore.QRect(70, 10, 110, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.Date = QtWidgets.QLabel(parent=self.Date_widget)
        self.Date.setGeometry(QtCore.QRect(10, 10, 60, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Date.setFont(font)
        self.Date.setObjectName("Date")
        self.Doctor_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.Doctor_widget.setGeometry(QtCore.QRect(250, 20, 271, 51))
        self.Doctor_widget.setObjectName("Doctor_widget")
        self.Doctor = QtWidgets.QLabel(parent=self.Doctor_widget)
        self.Doctor.setGeometry(QtCore.QRect(10, 10, 60, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Doctor.setFont(font)
        self.Doctor.setObjectName("Doctor")
        self.Doctor_name = QtWidgets.QComboBox(parent=self.Doctor_widget)
        self.Doctor_name.setGeometry(QtCore.QRect(90, 10, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Doctor_name.setFont(font)
        self.Doctor_name.setObjectName("Doctor_name")
        self.Doctor_name.addItem("")
        self.Doctor_name.addItem("")
        self.Doctor_name.addItem("")
        self.Calender = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.Calender.setGeometry(QtCore.QRect(20, 80, 461, 241))
        self.Calender.setAutoFillBackground(False)
        self.Calender.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.Calender.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.Calender.setProperty("showDropIndicator", True)
        self.Calender.setGridStyle(QtCore.Qt.PenStyle.DotLine)
        self.Calender.setRowCount(5)
        self.Calender.setObjectName("Calender")
        self.Calender.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        item.setFont(font)
        self.Calender.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Calender.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        self.Calender.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Calender.setItem(4, 2, item)
        # START
        self.Calender.setColumnWidth(0, 100) #Sætter bredden på kolonnerne
        self.Calender.setColumnWidth(1, 120)
        self.Calender.setColumnWidth(2, 240)
        self.Calender.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Fixed) #For at man ikke kan justere i linjerne på tabellen
        self.Calender.verticalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Fixed)
        header = self.Calender.horizontalHeader()
        header.setStyleSheet("background-color: rgb(200, 230, 255);") #Farve på header
        for i in range(self.Calender.rowCount()):
            self.Calender.setRowHeight(i, 45) #Sætter højden på hver række i tabellen
        #SLUT
        self.Calender.horizontalHeader().setVisible(True)
        self.Calender.horizontalHeader().setHighlightSections(True)
        self.Calender.verticalHeader().setVisible(False)
        self.Calender.verticalHeader().setHighlightSections(False)
        self.SearchCPR_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.SearchCPR_widget.setGeometry(QtCore.QRect(570, 80, 281, 71))
        self.SearchCPR_widget.setObjectName("SearchCPR_widget")
        self.CPR = QtWidgets.QLabel(parent=self.SearchCPR_widget)
        self.CPR.setGeometry(QtCore.QRect(10, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.CPR.setFont(font)
        self.CPR.setObjectName("CPR")
        self.CPR_inout = QtWidgets.QLineEdit(parent=self.SearchCPR_widget)
        self.CPR_inout.setGeometry(QtCore.QRect(70, 0, 200, 31))
        self.CPR_inout.setObjectName("CPR_inout")
        self.Search_CPR = QtWidgets.QPushButton(parent=self.SearchCPR_widget,clicked = lambda: self.openWindow())
        self.Search_CPR.setGeometry(QtCore.QRect(160, 40, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Search_CPR.setFont(font)
        self.Search_CPR.setObjectName("Search_CPR")
        EHR2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=EHR2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 24))
        self.menubar.setObjectName("menubar")
        self.menuClose = QtWidgets.QMenu(parent=self.menubar)
        self.menuClose.setObjectName("menuClose")
        self.menuReturn = QtWidgets.QMenu(parent=self.menubar)
        self.menuReturn.setObjectName("menuReturn")
        EHR2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=EHR2)
        self.statusbar.setObjectName("statusbar")
        EHR2.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuClose.menuAction())
        self.menubar.addAction(self.menuReturn.menuAction())

        self.retranslateUi(EHR2)
        QtCore.QMetaObject.connectSlotsByName(EHR2)

    def retranslateUi(self, EHR2):
        _translate = QtCore.QCoreApplication.translate
        EHR2.setWindowTitle(_translate("EHR2", "EHR - Electronic Health Record"))
        self.Date.setText(_translate("EHR2", "Date:"))
        self.Doctor.setText(_translate("EHR2", "Doctor:"))
        self.Doctor_name.setItemText(0, _translate("EHR2", "Peter Andersen"))
        self.Doctor_name.setItemText(1, _translate("EHR2", "Hanne Jensen"))
        self.Doctor_name.setItemText(2, _translate("EHR2", "Morten Knudsen"))
        item = self.Calender.verticalHeaderItem(0)
        item.setText(_translate("EHR2", "Patient 1"))
        item = self.Calender.verticalHeaderItem(1)
        item.setText(_translate("EHR2", "Patient 2"))
        item = self.Calender.verticalHeaderItem(2)
        item.setText(_translate("EHR2", "Patient 3"))
        item = self.Calender.verticalHeaderItem(3)
        item.setText(_translate("EHR2", "Patient 4"))
        item = self.Calender.verticalHeaderItem(4)
        item.setText(_translate("EHR2", "Patient 5"))
        item = self.Calender.horizontalHeaderItem(0)
        item.setText(_translate("EHR2", "Time"))
        item = self.Calender.horizontalHeaderItem(1)
        item.setText(_translate("EHR2", "CPR"))
        item = self.Calender.horizontalHeaderItem(2)
        item.setText(_translate("EHR2", "Reason of inquiry"))
        __sortingEnabled = self.Calender.isSortingEnabled()
        self.Calender.setSortingEnabled(False)
        item = self.Calender.item(0, 0)
        item.setText(_translate("EHR2", "9:00 - 9:30"))
        item = self.Calender.item(0, 1)
        item.setText(_translate("EHR2", "1234567890"))
        item = self.Calender.item(0, 2)
        item.setText(_translate("EHR2", "Rash on legs"))
        item = self.Calender.item(1, 0)
        item.setText(_translate("EHR2", "9:30 - 10:00"))
        item = self.Calender.item(1, 1)
        item.setText(_translate("EHR2", "1012988542"))
        item = self.Calender.item(1, 2)
        item.setText(_translate("EHR2", "Pregnancy"))
        item = self.Calender.item(2, 0)
        item.setText(_translate("EHR2", "10:00 - 11:00"))
        item = self.Calender.item(2, 1)
        item.setText(_translate("EHR2", "0510689764"))
        item = self.Calender.item(2, 2)
        item.setText(_translate("EHR2", "Fever and cough"))
        item = self.Calender.item(3, 0)
        item.setText(_translate("EHR2", "11:00 - 11:30"))
        item = self.Calender.item(3, 1)
        item.setText(_translate("EHR2", "0102569637"))
        item = self.Calender.item(3, 2)
        item.setText(_translate("EHR2", "Swollen throat"))
        item = self.Calender.item(4, 0)
        item.setText(_translate("EHR2", "13:30 - 14:00"))
        item = self.Calender.item(4, 1)
        item.setText(_translate("EHR2", "0706979858"))
        item = self.Calender.item(4, 2)
        item.setText(_translate("EHR2", "Birth control"))
        self.Calender.setSortingEnabled(__sortingEnabled)
        self.CPR.setText(_translate("EHR2", "CPR:"))
        self.Search_CPR.setText(_translate("EHR2", "Search CPR"))
        self.menuClose.setTitle(_translate("EHR2", "Close"))
        self.menuReturn.setTitle(_translate("EHR2", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EHR2 = QtWidgets.QMainWindow()
    ui = Ui_EHR2()
    ui.setupUi(EHR2)
    EHR2.show()
    sys.exit(app.exec())



